### PR TITLE
Solidus 1.2

### PR DESCRIPTION
**Pull request by papayaah**
@bryanmtl 

I had the spec in to check users with order token can still redeem gc's. 

Suggesting to merge this to master now.

cc @aamyot

### CODE REVIEW

**Comment by bryanmtl** [comment]
@mickeyren Should I expect these tests to be passing?

**Comment by papayaah** [comment]
sorry @bryanmtl  i changed a column value in the admin, but anyway should be good now.

**Comment by bryanmtl** [comment]
@mickeyren Merged!

**Comment by hugobast** [comment]
The Gemfile was never updated and references the branch still: https://github.com/glossier/glossier-v2/blob/master/Gemfile#L108

I'm opening a PR.

**Pull request merged**
